tasks:
  # - task: "rtdetr"
  #   subtasks:
  #     - type: "performance"
  #       engine_file: "rtdetr_r50vd_6x_coco_dynamic_fp16.trt"
  #       gpuid: 0
  # - task: "yolov10"
  #   subtasks:
  #     - type: "performance_v10"
  #       engine_file: "yolov10n.trt"
  #       gpuid: 0
  # - task: "yolo"
  #   subtasks:
  #     - type: "batch_inference"
  #       engine_file: "/home/e300/mahmood/code/Linfer/workspace/yolov8s.trt"
  #       gpuid: 0
  #       yolo_type: "V8"
  #       input_dir: "/home/e300/mahmood/code/mLinfer/workspace/imgs"
  #       output_dir: "/home/e300/mahmood/code/mLinfer/workspace/result_images"
  #     - type: "performance"
  #       engine_file: "/home/e300/mahmood/code/Linfer/workspace/yolov8s.trt"
  #       gpuid: 0
  #       yolo_type: "V8"
  #       input_dir: "/home/e300/mahmood/code/mLinfer/workspace/imgs"
  #     - type: "single_inference"
  #       engine_file: "/home/e300/mahmood/code/Linfer/workspace/yolov8s.trt"
  #       gpuid: 0
  #       yolo_type: "V8"
  #       input_img: "/home/e300/Downloads/1684008869189.jpg"
  #       output_img_path: "/home/e300/mahmood/code/mLinfer/workspace/result_images_single/1684008869189.jpg"
  - task: "track"
    subtasks:
      - type: "inference_bytetrack"
        engine_file: "/home/e300/mahmood/code/Linfer/workspace/yolov8s.trt"
        gpuid: 0
        yolo_type: "V8"
        video_file: "/home/e300/mahmood/code/Linfer/workspace/videos/snow.mp4"
        output_save_path: ""
  # - task: "yolop"
  #   subtasks:
  #     - type: "inference_yolop"
  #       engine_file: "yolopv2-480x640.trt"
  #       yolo_type: "V2"
  #       gpuid: 0
  # - task: "seg"
  #   subtasks:
  #       - type: "inference_seg"
  #         engine_file: "ppliteseg_stdc2.trt"
  #         gpuid: 0